---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
  namespace: "default"
spec:
  type: clusterIP
  selector:
    name: dev-vault
    app: vault
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
