apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: basic-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basic-example 
    spec:
      serviceAccountName: app-auth
      containers:
        - name: app 
          image: "kawsark/vault-example-init:0.0.3"
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ADDR
              value: "http://vault.therealk.com:8200"
